### ISSUE TITLE
remove "mon"

### ISSUE THREAD

**Issue by r0x5r** [Gurpreet06/Wifi-Crack#3]
pajji remove mon to you srcript why you add "mon" when user add full intername vai cli

**Comment by Gurpreet06** [comment]
It cannot be deleted, because the name of the interface is different in each computer, for example in some laptops if we go directly from the network adapter that comes inside the laptop then when we put that adapter in monitor mode sometimes "mon" is added at the end with the name of the adapter and sometimes that does not happen. But this script has contemplated to check if it is with "mon" or without "mon".
